version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/python:3.8'  # replace with the Docker image that fits your needs
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Here you can run tests or any other pre-deployment steps
      - run:
          name: Install Railway CLI
          command: |
            curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh
      - run:
          name: Deploy to Railway
          command: |
            echo $RAILWAY_TOKEN | railway login
            railway up --detach $RAILWAY_PROJECT_ID
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
