version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/python:3.8'  # replace with the Docker image that fits your needs
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run:
          name: Install Railway CLI
          command: |
            curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh
            echo 'export PATH=$HOME/.railway/bin:$PATH' >> $BASH_ENV
      - run:
          name: Deploy to Railway
          command: |
            railway up --detach

  deploy:
    docker:
      - image: 'cimg/python:3.8'  # replace with the Docker image that fits your needs
    steps:
      - checkout
      - run:
          name: Install Railway CLI
          command: |
            curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh
            echo 'export PATH=$HOME/.railway/bin:$PATH' >> $BASH_ENV
      - run:
          name: Redeploy to Railway
          command: |
            railway up --detach

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/   # Allow all tags
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/   # Ignore all branches

